### PR TITLE
Logo alignment fix?

### PR DESCRIPTION
**Pull request by KALoneNinja**
I believe this will make the logo center-align right for all users.

### CODE REVIEW

**Comment by An0n3m0us** [comment]
Does it matter that it isn't centered on a widescreen?:
image

**Comment by KALoneNinja** [comment]
I was fixing the problem with the KA extension or on mobile, the logo didn't line up with the ellipse gradient. The widescreen shouldn't be a big deal, but I can fix it if you want.

**Comment by An0n3m0us** [comment]
If you can, that would be good. Otherwise, it matters little.

**Comment by KALoneNinja** [comment]
I believe the alignment was in the formatting pr.

**Pull request closed without merging**
